### ISSUE TITLE
哔咔

### ISSUE THREAD

**Issue by buiawpkgew1** [zhonghuaifang/My-Actions#8]
能添加查看`等级`和`当前经验`吗

**Comment by zhonghuaifang** [comment]
这个脚本最开始也是我拉取别人的，因为当时那个人很久没更新了，有bug，还有一些我需要的东西他没有，所以才单独拉取自己修改使用，但是我用到的只有`贴吧`,`b站`,`小米运动`,`中国电信`，`哔咔`我没用过，晚上我回去看一下，是要加入到通知里面吗

**Comment by buiawpkgew1** [comment]
> 这个脚本最开始也是我拉取别人的，因为当时那个人很久没更新了，有bug，还有一些我需要的东西他没有，所以才单独拉取自己修改使用，但是我用到的只有`贴吧`,`b站`,`小米运动`,`中国电信`，`哔咔`我没用过，晚上我回去看一下，是要加入到通知里面吗

是加到通知里

**Comment by buiawpkgew1** [comment]
[哔咔api](https://www.apifox.cn/apidoc/shared-44da213e-98f7-4587-a75e-db998ed067ad/api-27878547)

**Comment by zhonghuaifang** [comment]
@buiawpkgew1 最近太忙了，上午趁领导不在，加上了
